/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Lenovo
 */
public class View_Imc extends javax.swing.JPanel {

    /**
     * Creates new form View_Imcs
     */
    public View_Imc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jp_datos = new javax.swing.JPanel();
        jt_peso = new javax.swing.JTextField();
        jc_sexo = new javax.swing.JComboBox<>();
        peso = new javax.swing.JLabel();
        jl_sexo = new javax.swing.JLabel();
        jt_altura = new javax.swing.JTextField();
        jl_edad = new javax.swing.JLabel();
        jbtn_calcular = new javax.swing.JButton();
        jt_nombre = new javax.swing.JTextField();
        altura = new javax.swing.JLabel();
        jt_edad = new javax.swing.JTextField();
        jl_nombre = new javax.swing.JLabel();
        jp_resultados = new javax.swing.JPanel();
        jl_nombre2 = new javax.swing.JLabel();
        jl_sexo2 = new javax.swing.JLabel();
        jl_edad2 = new javax.swing.JLabel();
        jl_peso2 = new javax.swing.JLabel();
        jl_altura2 = new javax.swing.JLabel();
        jt_nombre2 = new javax.swing.JTextField();
        jt_sexo2 = new javax.swing.JTextField();
        jt_edad2 = new javax.swing.JTextField();
        jt_peso2 = new javax.swing.JTextField();
        jt_altura2 = new javax.swing.JTextField();
        jl_imc = new javax.swing.JLabel();
        jl_estado = new javax.swing.JLabel();
        jt_estado = new javax.swing.JTextField();
        jt_imc = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calcula tu Indice de Masa Corporal");

        jp_datos.setBackground(new java.awt.Color(204, 204, 255));
        jp_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true), "Datos ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        jt_peso.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jc_sexo.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jc_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Hombre", "Mujer" }));

        peso.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        peso.setForeground(new java.awt.Color(0, 153, 153));
        peso.setText("Peso");

        jl_sexo.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jl_sexo.setForeground(new java.awt.Color(0, 153, 153));
        jl_sexo.setText("Sexo");

        jt_altura.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jt_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_alturaActionPerformed(evt);
            }
        });

        jl_edad.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jl_edad.setForeground(new java.awt.Color(0, 153, 153));
        jl_edad.setText("Edad");

        jbtn_calcular.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_calcular.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbtn_calcular.setForeground(new java.awt.Color(0, 102, 102));
        jbtn_calcular.setText("Calcular");
        jbtn_calcular.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jbtn_calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_calcularActionPerformed(evt);
            }
        });

        jt_nombre.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        altura.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        altura.setForeground(new java.awt.Color(0, 153, 153));
        altura.setText("Altura");

        jt_edad.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jl_nombre.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jl_nombre.setForeground(new java.awt.Color(0, 153, 153));
        jl_nombre.setText("Nombre");

        javax.swing.GroupLayout jp_datosLayout = new javax.swing.GroupLayout(jp_datos);
        jp_datos.setLayout(jp_datosLayout);
        jp_datosLayout.setHorizontalGroup(
            jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jp_datosLayout.createSequentialGroup()
                        .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_nombre)
                            .addComponent(jl_sexo)
                            .addComponent(jl_edad)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_peso)
                            .addComponent(jc_sexo, 0, 150, Short.MAX_VALUE)
                            .addComponent(jt_edad)
                            .addComponent(jt_nombre)
                            .addComponent(jt_altura))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_datosLayout.setVerticalGroup(
            jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_sexo)
                    .addComponent(jc_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_edad)
                    .addComponent(jt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso)
                    .addComponent(jt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altura)
                    .addComponent(jt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jbtn_calcular)
                .addGap(24, 24, 24))
        );

        jp_resultados.setBackground(new java.awt.Color(204, 204, 255));
        jp_resultados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true)), "Resultados", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jl_nombre2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jl_nombre2.setForeground(new java.awt.Color(0, 153, 153));
        jl_nombre2.setText("Nombre");

        jl_sexo2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jl_sexo2.setForeground(new java.awt.Color(0, 153, 153));
        jl_sexo2.setText("Sexo");

        jl_edad2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jl_edad2.setForeground(new java.awt.Color(0, 153, 153));
        jl_edad2.setText("Edad");

        jl_peso2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jl_peso2.setForeground(new java.awt.Color(0, 153, 153));
        jl_peso2.setText("Peso");

        jl_altura2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jl_altura2.setForeground(new java.awt.Color(0, 153, 153));
        jl_altura2.setText("Altura");

        jt_nombre2.setEditable(false);
        jt_nombre2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jt_sexo2.setEditable(false);
        jt_sexo2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jt_edad2.setEditable(false);
        jt_edad2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jt_peso2.setEditable(false);
        jt_peso2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jt_peso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_peso2ActionPerformed(evt);
            }
        });

        jt_altura2.setEditable(false);
        jt_altura2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jl_imc.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jl_imc.setForeground(new java.awt.Color(0, 153, 153));
        jl_imc.setText("IMC");

        jl_estado.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jl_estado.setForeground(new java.awt.Color(0, 153, 153));
        jl_estado.setText("Estado");

        jt_estado.setEditable(false);
        jt_estado.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jt_imc.setEditable(false);
        jt_imc.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jt_imc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_imcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_resultadosLayout = new javax.swing.GroupLayout(jp_resultados);
        jp_resultados.setLayout(jp_resultadosLayout);
        jp_resultadosLayout.setHorizontalGroup(
            jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_resultadosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_resultadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_sexo2)
                            .addComponent(jl_edad2)
                            .addComponent(jl_peso2)
                            .addComponent(jl_altura2)
                            .addComponent(jl_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jt_sexo2)
                            .addComponent(jt_edad2)
                            .addComponent(jt_peso2)
                            .addComponent(jt_altura2)))
                    .addGroup(jp_resultadosLayout.createSequentialGroup()
                        .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_imc)
                            .addComponent(jl_estado))
                        .addGap(55, 55, 55)
                        .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_estado)
                            .addComponent(jt_imc))))
                .addGap(42, 42, 42))
        );
        jp_resultadosLayout.setVerticalGroup(
            jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_resultadosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_resultadosLayout.createSequentialGroup()
                        .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_sexo2)
                            .addComponent(jt_sexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_edad2)
                            .addComponent(jt_edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jl_peso2))
                    .addComponent(jt_peso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_altura2)
                    .addComponent(jt_altura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_imc)
                    .addComponent(jt_imc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_estado)
                    .addComponent(jt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jp_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_alturaActionPerformed

    private void jbtn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_calcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_calcularActionPerformed

    private void jt_peso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_peso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_peso2ActionPerformed

    private void jt_imcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_imcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_imcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel altura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton jbtn_calcular;
    public javax.swing.JComboBox<String> jc_sexo;
    private javax.swing.JLabel jl_altura2;
    private javax.swing.JLabel jl_edad;
    private javax.swing.JLabel jl_edad2;
    private javax.swing.JLabel jl_estado;
    private javax.swing.JLabel jl_imc;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_nombre2;
    private javax.swing.JLabel jl_peso2;
    private javax.swing.JLabel jl_sexo;
    private javax.swing.JLabel jl_sexo2;
    private javax.swing.JPanel jp_datos;
    public javax.swing.JPanel jp_resultados;
    public javax.swing.JTextField jt_altura;
    public javax.swing.JTextField jt_altura2;
    public javax.swing.JTextField jt_edad;
    public javax.swing.JTextField jt_edad2;
    public javax.swing.JTextField jt_estado;
    public javax.swing.JTextField jt_imc;
    public javax.swing.JTextField jt_nombre;
    public javax.swing.JTextField jt_nombre2;
    public javax.swing.JTextField jt_peso;
    public javax.swing.JTextField jt_peso2;
    public javax.swing.JTextField jt_sexo2;
    public javax.swing.JLabel peso;
    // End of variables declaration//GEN-END:variables
}
