/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Lenovo
 */
public class View_Operaciones extends javax.swing.JPanel {

    /**
     * Creates new form View_Operacioness
     */
    public View_Operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmvc3 = new javax.swing.JPanel();
        jl_numero1 = new javax.swing.JLabel();
        jl_numero2 = new javax.swing.JLabel();
        jtx_numero1 = new javax.swing.JTextField();
        jtx_numero2 = new javax.swing.JTextField();
        jl_resultado = new javax.swing.JLabel();
        jtx_resultado = new javax.swing.JTextField();
        btn_increment = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_decrement = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_modulo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jpmvc3.setBackground(new java.awt.Color(204, 204, 255));

        jl_numero1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_numero1.setText("Número 1");

        jl_numero2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_numero2.setText("Número 2");

        jtx_numero1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtx_numero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtx_numero1KeyTyped(evt);
            }
        });

        jtx_numero2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtx_numero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtx_numero2KeyTyped(evt);
            }
        });

        jl_resultado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_resultado.setText("Resultado");

        jtx_resultado.setEditable(false);
        jtx_resultado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btn_increment.setBackground(new java.awt.Color(204, 255, 204));
        btn_increment.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btn_increment.setText("+");

        btn_dividir.setBackground(new java.awt.Color(204, 255, 204));
        btn_dividir.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btn_dividir.setText("/");

        btn_decrement.setBackground(new java.awt.Color(204, 255, 204));
        btn_decrement.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btn_decrement.setText("-");

        btn_multiplicar.setBackground(new java.awt.Color(204, 255, 204));
        btn_multiplicar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btn_multiplicar.setText("*");

        btn_modulo.setBackground(new java.awt.Color(204, 255, 204));
        btn_modulo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btn_modulo.setText("%");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Operaciones ");

        javax.swing.GroupLayout jpmvc3Layout = new javax.swing.GroupLayout(jpmvc3);
        jpmvc3.setLayout(jpmvc3Layout);
        jpmvc3Layout.setHorizontalGroup(
            jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmvc3Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_numero2)
                    .addComponent(jl_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_numero1)
                    .addComponent(btn_increment, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpmvc3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtx_numero1)
                            .addComponent(jtx_numero2)
                            .addComponent(jtx_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpmvc3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_decrement, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btn_modulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpmvc3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        jpmvc3Layout.setVerticalGroup(
            jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmvc3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addGap(61, 61, 61)
                .addGroup(jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero1)
                    .addComponent(jtx_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero2)
                    .addComponent(jtx_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_resultado)
                    .addComponent(jtx_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jpmvc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_increment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_decrement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpmvc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpmvc3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtx_numero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_numero1KeyTyped

    }//GEN-LAST:event_jtx_numero1KeyTyped

    private void jtx_numero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_numero2KeyTyped

    }//GEN-LAST:event_jtx_numero2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_decrement;
    public javax.swing.JButton btn_dividir;
    public javax.swing.JButton btn_increment;
    public javax.swing.JButton btn_modulo;
    public javax.swing.JButton btn_multiplicar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jl_numero1;
    private javax.swing.JLabel jl_numero2;
    private javax.swing.JLabel jl_resultado;
    private javax.swing.JPanel jpmvc3;
    public javax.swing.JTextField jtx_numero1;
    public javax.swing.JTextField jtx_numero2;
    public javax.swing.JTextField jtx_resultado;
    // End of variables declaration//GEN-END:variables
}
